### ISSUE TITLE
robots.txt files are not being respected correctly

### ISSUE THREAD

**Issue by div72** [spider-rs/spider#184]
I have a [robots.txt](https://div72.xyz/robots.txt) not being respected by spider-rs currently.

Upon debugging there seems to be two issues:
1. URLs are not getting passed to the `RobotFileParser` correctly. It seems that `RobotFileParser` is expecting just paths while `Website::is_allowed_robots` is passing whole URLs: https://github.com/spider-rs/spider/blob/4b8a604197e9de2ce92ee4371263397d746e8911/spider/src/website.rs#L401-L407

Here's GDB output from the can_fetch call inside the function:
```
(gdb) p url_str
$16 = "https://div72.xyz"
(gdb) p default_entry.allowance(url_str)
$17 = true
(gdb) p default_entry.allowance("/")
$18 = false
(gdb) p default_entry.allowance("")
$19 = true
```

2. `Website::is_allowed_robots` is not passing the user-agent to the `RobotFileParser`. The `'*'` parameter in the code above should be `self.configuration.user_agent` rather than `'*'`.

**Comment by j-mendez** [comment]
fixed in `1.95.21` thanks!

**Comment by ubedan** [comment]
I think it's still not quite right...

I had a robots.txt file that had:

Disallow: /careers/login

And I got a scrape:

...url.com%2Fcareers%2Flogin%3FreturnTo%3D%2Fcareers%2Ffield%2Dsales.html 

Which decodes to:

...url.com/careers/login?returnTo=/careers/field-sales.html


Does everyone want me to take a stab at fixing it?

**Comment by j-mendez** [comment]
> I think it's still not quite right...
> 
> 
> 
> I had a robots.txt file that had:
> 
> 
> 
> Disallow: /careers/login
> 
> 
> 
> And I got a scrape:
> 
> 
> 
> ...url.com%2Fcareers%2Flogin%3FreturnTo%3D%2Fcareers%2Ffield%2Dsales.html 
> 
> 
> 
> Which decodes to:
> 
> 
> 
> ...url.com/careers/login?returnTo=/careers/field-sales.html
> 
> 
> 
> 
> 
> Does everyone want me to take a stab at fixing it?

Hello, what website did you use and what user-agent? This will help us test etc.

**Comment by ubedan** [comment]
Oxide.Computer, and I was using the download.rs example.

**Comment by j-mendez** [comment]
@ubedan  https://github.com/spider-rs/spider/commit/f32820c8ca265d175cc05745a605f30c422fd369 fixed in `1.98.3` ty

**Comment by ubedan** [comment]
Wow!  Awesome!  So fast!!!   Thanks!
